name 'sysauth'
maintainer 'Mike McCarthy'
maintainer_email 'mdmccarthyuk@gmail.com'
license 'all_rights'
description 'Installs/Configures sysauth'
long_description 'Installs/Configures sysauth'
version '0.3.1'
