name 'sysauth'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures sysauth'
long_description 'Installs/Configures sysauth'
version '0.1.0'
